import { ReduxProvider } from "@/redux/reduxProvider";

import AuthProvider from "./provider";
import AuthContextProvider from "./contexts/authContext";
import Footer from "./components/footer/footer";

import ClientRootLayout from "./components/client-root-layout/clientRootLayout";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ToastContainer } from "react-toastify";

import "./globals.css";
import Navbar from "./components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Library Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AuthContextProvider>
            <ReduxProvider>
              <ToastContainer />
              {/* <Navbar /> */}
              {children}
              <Footer />
            </ReduxProvider>
          </AuthContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
